version: 2
jobs: 
  build:
    docker: 
      - image: circleci/python:3.7.0  
    working_directory: ~/knn 
    steps:
      - checkout 
      - run: 
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip3 install -r requirements.txt
            jupyter nbconvert --ExecutePreprocessor.kernel_name=python3 --to notebook --execute knn.ipynb
            sh get_html.sh
      - store_artifacts:
          path: ~/knn/knn.html
          destination: knn.html
