version: 2
jobs: 
  build:
    machine: true 
    working_directory: ~/knn 
    steps:
      - checkout 
      - run: 
          name: install dependencies
          command: |
            python3.5 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
