version: 2
jobs: 
  build:
    working_directory: ~/knn
    docker: 
      - image: circleci/python:3.5.1 
    steps:
      - checkout 
      - run: 
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - run:
          name: execute
          command: |
            . venv/bin/activate
            jupyter nbconvert --ExecutePreprocessor.kernel_name=python3 --execute knn.ipynb
            sh get_html.sh
          paths:
            - "venv"
      - store_artifacts:
          path: ~/knn/knn.html
          destination: knn.html
