version: 2
jobs: 
  build:
    machine: 
        python:
            version: 3.5.2 
    working_directory: ~/knn 
    steps:
      - checkout 
      - run: 
          name: install dependencies
          command: |
            pyenv local 3.5.2 
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
            sh get_html.sh
