version: 2
jobs: 
  build:
    machine: 
       image: circleci/python:3.5.2 
    working_directory: ~/knn 
    steps:
      - checkout 
      - run: 
          name: install dependencies
          command: |
            pyenv local 3.5.2 
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
            jupyter nbconvert --ExecutePreprocessor.kernel_name=python3 --to notebook --execute knn.ipynb
            sh get_html.sh
      - store_artifacts:
          path: ~/knn/knn.html
          destination: knn.html
